# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=' ', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='z', max_length=200),
            preserve_default=False,
        ),
    ]
