# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170824_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='upload',
            field=models.FileField(default='z', upload_to=video.models.user_directory_path),
            preserve_default=False,
        ),
    ]
